# Generated by Django 5.2.3 on 2025-06-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_status_alter_transaction_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('successful', 'successful')], max_length=10),
        ),
    ]
