# Generated by Django 5.2.3 on 2025-06-19 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='eth_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='wallet',
            name='solana_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='wallet',
            name='ton_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='wallet',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bitcoin_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=16),
        ),
        migrations.CreateModel(
            name='DepositConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('crypto', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT (Tether)'), ('BNB', 'BNB')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('receipt', models.FileField(upload_to='deposit_receipts/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
