# Generated by Django 5.2.3 on 2025-06-22 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usertousertransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_bonus_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
