# Generated by Django 5.2.3 on 2025-06-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_wallet_last_bonus_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bnb_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='depositconfirmation',
            name='crypto',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT (Tether)'), ('BNB', 'BNB'), ('SOL', 'SOL'), ('TON', 'TON')], max_length=10),
        ),
    ]
