# Generated by Django 5.2.3 on 2025-06-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_wallet_bnb_balance_alter_depositconfirmation_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bgb_balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='doge_balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='sui_balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='tron_balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='usdc_balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='usertousertransfer',
            name='crypto',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT'), ('TON', 'Toncoin'), ('SOL', 'Solana'), ('BNB', 'binancecoin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bitcoin_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='eth_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='solana_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ton_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
