# Generated by Django 5.2.3 on 2025-06-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_wallet_bgb_balance_wallet_doge_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositconfirmation',
            name='crypto',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT (Tether)'), ('BNB', 'BNB'), ('TON', 'TON'), ('SOL', 'SOL'), ('USDC', 'USDC'), ('SUI', 'SUI'), ('DOGE', 'DOGE'), ('BGB', 'BGB'), ('TRON', 'TRON')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usertousertransfer',
            name='crypto',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT'), ('TON', 'Toncoin'), ('SOL', 'Solana'), ('BNB', 'binancecoin'), ('USDC', 'USDC'), ('SUI', 'SUI'), ('DOGE', 'DOGE'), ('BGB', 'BGB'), ('TRON', 'TRON')], max_length=10),
        ),
    ]
