# Generated by Django 5.2.3 on 2025-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_depositconfirmation_crypto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
