# Generated by Django 5.2.3 on 2025-06-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_wallet_transaction_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_pin',
        ),
    ]
