# Generated by Django 5.0 on 2025-06-28 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_transaction_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bgb_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bnb_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='doge_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='eth_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='solana_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='sui_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ton_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='tron_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='usdc_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(default='0')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
