# Generated by Django 5.0 on 2025-06-28 08:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_transaction_status_alter_wallet_bgb_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bgb_balance',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bnb_balance',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='doge_balance',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='eth_balance',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='solana_balance',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='sui_balance',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ton_balance',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='tron_balance',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='usdc_balance',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
    ]
