# Generated by Django 5.1.5 on 2025-07-22 05:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_wallet_bgb_balance_alter_wallet_bnb_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=14),
        ),
    ]
